### ISSUE TITLE
[NEW]: Versioni Windows

### ISSUE THREAD

**Issue by EduBic** [LeafSWE/HookDiary#5]
Sarebbe meglio suddividere il repository con due cartelle con all'interno i file con le differenti versioni richieste, così da non richiedere ad ogni aggionamento la modifica manuale per chi utilizza windows.

**Comment by oeconti** [comment]
Che differenze ci sono su windows?

**Comment by EduBic** [comment]
Aggiunta di tale riga:

`PERL=/c/Perl64/bin/perl.exe`

e uso di `$PERL` al posto di `perl`.

Modifiche da effettuare in _post-commit.txt_ e _manualDiaryGenarator.sh_. Anche su Mac in teoria ci sono delle variazioni da fare.

**Comment by oeconti** [comment]
Lo script non verrà mantenuto per windows.
